backend:
  branch: master
  name: git-gateway
collections:
  - create: true
    fields:
      - label: 'Display name (such as your full name)'
        name: title
        widget: string
      - label: 'Position or tagline (such as Professor of AI)'
        name: role
        required: false
        widget: string
      - default: avatar
        label: 'Avatar (upload an image named `avatar.jpg/png`)'
        media_library:
          config:
            multiple: false
        name: avatar_filename
        required: false
        widget: image
      - label: 'Short biography (shown in author boxes)'
        name: bio
        required: false
        widget: string
      - label: 'Full biography (shown in About widget)'
        name: body
        required: false
        widget: markdown
      - label: 'Interests (shown in About widget)'
        name: interests
        required: false
        widget: list
      - fields:
          - label: Link
            name: link
            widget: string
          - label: 'Icon pack'
            multiple: false
            name: icon_pack
            options:
              - label: None
                value: ""
              - label: Solid
                value: fas
              - label: Regular
                value: far
              - label: Brand
                value: fab
              - label: Academic
                value: ai
            widget: select
          - label: "Icon (see https://sourcethemes.com/academic/docs/page-builder/#icons)"
            name: icon
            widget: string
        label: 'Social links'
        name: social
        required: false
        widget: list
      - fields:
          - label: Organization
            name: name
            required: true
            widget: string
          - label: Link
            name: url
            required: false
            widget: string
        label: 'Organizations you belong to or are affiliated with (shown in About
          widget)'
        name: organizations
        required: false
        widget: list
      - fields:
          - fields:
              - label: Course
                name: course
                required: true
                widget: string
              - label: Institution
                name: institution
                required: true
                widget: string
              - label: Year
                name: year
                required: false
                valueType: int
                widget: number
            label: Courses
            name: courses
            required: false
            widget: list
        label: Education
        name: education
        required: false
        widget: object
      - label: 'Email (to use a Gravatar.com avatar)'
        name: email
        required: false
        widget: string
      - default: false
        label: 'Super user (is this the primary site user?)'
        name: superuser
        widget: boolean
      - label: 'User groups (only for organization websites)'
        name: user_groups
        required: false
        widget: list
    folder: content/authors
    label: Authors
    label_singular: Author
    name: authors
    path: {{slug}}/_index
  - create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: 'Publish this page on'
        name: date
        widget: datetime
      - label: Summary
        name: summary
        widget: markdown
      - default: false
        label: Draft
        name: draft
        widget: boolean
      - default: false
        label: Featured
        name: featured
        widget: boolean
      - label: Authors
        name: authors
        required: false
        widget: list
      - label: Tags
        name: tags
        required: false
        widget: list
      - label: Categories
        name: categories
        required: false
        widget: list
      - label: Projects
        name: projects
        required: false
        widget: list
      - fields:
          - default: featured
            label: 'Upload an image named `featured.jpg/png`'
            media_library:
              config:
                multiple: false
            name: filename
            widget: image
          - label: Caption
            name: caption
            required: false
            widget: string
          - label: 'Description for screen readers'
            name: alt_text
            required: false
            widget: string
          - default: Smart
            label: 'Where''s the focal point in the image? Smart, Center, TopLeft,
              Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.'
            name: focal_point
            required: false
            widget: string
          - default: false
            label: 'Thumbnail Only?'
            name: preview_only
            widget: boolean
        label: 'Featured Image'
        name: image
        required: false
        widget: object
    folder: content/post
    label: Posts
    label_singular: Post
    name: posts
    path: {{slug}}/index
  - create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Abstract
        name: abstract
        widget: text
      - label: Where
        name: location
        widget: text
      - label: From
        name: date
        widget: datetime
      - default: ""
        label: To
        name: date_end
        widget: datetime
      - default: false
        label: 'All day event?'
        name: all_day
        widget: boolean
      - fields:
          - label: Link
            name: url
            widget: string
          - label: 'Link text'
            name: name
            required: false
            widget: string
          - label: 'Icon pack'
            multiple: false
            name: icon_pack
            options:
              - label: None
                value: ""
              - label: Solid
                value: fas
              - label: Regular
                value: far
              - label: Brand
                value: fab
              - label: Academic
                value: ai
            required: false
            widget: select
          - label: "Icon (see https://sourcethemes.com/academic/docs/page-builder/#icons)"
            name: icon
            required: false
            widget: string
        label: Links/Tickets
        name: links
        required: false
        widget: list
      - label: Event
        name: event
        widget: string
      - label: 'Event link'
        name: event_url
        widget: string
      - label: 'Publish this page on'
        name: publishDate
        widget: datetime
      - label: 'Markdown slides (reference a deck in ''content/slides/'')'
        name: slides
        required: false
        widget: string
      - default: false
        label: Draft
        name: draft
        widget: boolean
      - default: false
        label: Featured
        name: featured
        widget: boolean
      - label: Authors
        name: authors
        required: false
        widget: list
      - label: Tags
        name: tags
        required: false
        widget: list
      - label: Categories
        name: categories
        required: false
        widget: list
      - label: 'Projects (reference projects in ''content/project/'')'
        name: projects
        required: false
        widget: list
      - fields:
          - default: featured
            label: 'Upload an image named `featured.jpg/png`'
            media_library:
              config:
                multiple: false
            name: filename
            widget: image
          - label: Caption
            name: caption
            required: false
            widget: string
          - label: 'Description for screen readers'
            name: alt_text
            required: false
            widget: string
          - default: Smart
            label: 'Where''s the focal point in the image? Smart, Center, TopLeft,
              Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.'
            name: focal_point
            required: false
            widget: string
          - default: false
            label: 'Thumbnail Only?'
            name: preview_only
            widget: boolean
        label: 'Featured Image'
        name: image
        required: false
        widget: object
      - label: Details
        name: body
        widget: markdown
    folder: content/talk
    label: Talks
    label_singular: Talk
    name: talks
    path: {{slug}}/index
  - files:
      - fields:
          - label: Title
            name: title
            widget: string
          - label: 'Publish Date'
            name: date
            widget: datetime
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Summary
            name: summary
            widget: markdown
          - default: false
            label: Draft
            name: draft
            required: false
            widget: boolean
          - label: Body
            name: body
            widget: markdown
        file: content/privacy.md
        label: 'Privacy Policy'
        name: privacy
      - fields:
          - label: Title
            name: title
            widget: string
          - label: 'Publish Date'
            name: date
            widget: datetime
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Summary
            name: summary
            widget: markdown
          - default: false
            label: Draft
            name: draft
            required: false
            widget: boolean
          - label: Body
            name: body
            widget: markdown
        file: content/terms.md
        label: Terms
        name: terms
    label: Pages
    name: pages
media_folder: static/img/
public_folder: img
