---
name: Deploy GitHub Pages

"on":
  push:
    branches:
      - master
  workflow_dispatch:

permissions: {}

concurrency:
  group: pages
  cancel-in-progress: false

env:
  PAGES_ARTIFACT_NAME: >-
    github-pages-${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  build:
    name: Build Pages artifact
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pages: write
    steps:
      - name: Checkout repository
        # v7.0.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Configure GitHub Pages
        # v6.0.0
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      - name: Upload GitHub Pages artifact
        # v5.0.0
        uses: >-
          actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          name: ${{ env.PAGES_ARTIFACT_NAME }}
          path: .
          include-hidden-files: true

  deploy:
    name: Deploy GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        # v5.0.0
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
        with:
          artifact_name: ${{ env.PAGES_ARTIFACT_NAME }}
